version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: basketmanagementapi-tests-db-integration
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Str0ng!Passw0rd"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Str0ng!Passw0rd", "-C", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

